WordPress - MySQL connection via VPN!
==================================== 
 
Βασικός στόχος της εργασίας είναι η ανάπτυξη μιας υπηρεσίας σε νεφοϋπολογιστική υποδομή χρησιμοποιώντας μεθόδους εικονικοποίησης που παρέχει η πλατφόρμα του Docker. Κύριο χαρακτηριστικό είναι η εξ’ αποστάσεως επικοινωνία δύο διαφορετικών υπολογιστικών συστημάτων με σκοπό την ταυτόχρονη και παράλληλη εκτέλεση δύο διαφορετικών μικροϋπηρεσιών. Για την πραγματοποίηση της παραπάνω διεργασίας χρησιμοποιήθηκαν οι τεχνολογίες των εικονικών δικτύων VPN, το ψηφιακό εργαστήριο swarmlab.io και το IaaS Οkeanos. + 
 + 
 +

VPN + 
^^^^^ 
Προκειμένου να δημιουργηθεί ο δίαυλος επικοινωνίας μεταξύ των μηχανών και να επιτευχθεί η ανταλλαγή πληροφοριών των δύο απαιτήθηκε η διασύνδεσή τους κάτω από ένα VPN. + 
Για την κρυπτογράφηση αυτού έγινε η χρήση του open source πρωτοκόλλου επικοινωνίας *wireguard*, μέσω του οποίου πραγματοποιήθηκε η ανταλλαγή κλειδιών, το απαραίτητο tunneling και η έξοδος στο Διαδίκτυο μέσω του UDP.
 + 
 


Wordpress +  
^^^^^^^^^^
H microservice που επιλέχθηκε να ανέβει μέσω του εικονικού εργαστηρίου swarmlab είναι το *wordpress*. Βασική του λειτουργία είναι η δημιουργία και ανάρτηση ιστοτόπων, blog και εφαρμογών στο Διαδίκτυο. Ακόμα, εξαιτίας της αρχιτεκτονικής της και της δυνατήτητάς της να διαχειρίζεται τα δεδομένα αποτελεί την βάση για πολλές άλλες υπηρεσίες και εφαρμογές.
Το wordpress, το οποίο, ουσιαστικά βρίσκεται στο τοπικό μας μηχάνημα τρέχει στην διεύθυνση 
----
localhost:42861
----
 
 
MySQL + 
^^^^^^
Σε συνεργασία με το wordpress και χρησιμοποιώντας το ιδιωτικό δίκτυο, που δημιουργεί το VPN, τρέχει και η microservice διαχείρισης βάσεων δεδομένων *mysql*.
H mySQL βρίσκεται στο σε docker container και εκτελείται στο νέφος από το μηχάνημα του Okeanos.
Ο σκοπός της ύπαρξής της είναι να λαμβάνει και να αποθηκεύει σε βάση δεδομένων ό,τι πληροφορία παράγεται από το wordpress εφόσον αποσταλεί σε αυτή. 
    + 

Στοιχεία βάσης δεδομένων:
----
ip address:  83.212.80.188:3307
username:    wordpress
password:    wordpress
----
 
Με βάση τα παραπάνω, έχει δημιουργηθεί ένα περιβάλλον κλειστού, ιδιωτικού δικτύου ανάμεσα σε δύο ανεξάρτητα υπολογιστικά συστήματα τα οποία τρέχουν το καθένα μια διαφορετική μικροϋπηρεσία που παρέχουν τη δυνατότητα εκτέλεσης μιας ολοκληρωμένης υπηρεσίας.  



















      








